// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MovieAPI_Context.Model
{
    public partial class MovieContext : DbContext
    {
        public MovieContext()
        {
        }

        public MovieContext(DbContextOptions<MovieContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TblActor> TblActors { get; set; }
        public virtual DbSet<TblMovie> TblMovies { get; set; }
        public virtual DbSet<TblProducer> TblProducers { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TblActor>(entity =>
            {
                entity.HasKey(e => e.ActorId);

                entity.ToTable("tblActor");

                entity.Property(e => e.ActorId)
                    .ValueGeneratedNever()
                    .HasColumnName("ActorID");

                entity.Property(e => e.ActorName).HasMaxLength(50);

                entity.Property(e => e.Dob)
                    .HasColumnType("date")
                    .HasColumnName("DOB");

                entity.Property(e => e.Gender)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .IsFixedLength();
            });

            modelBuilder.Entity<TblMovie>(entity =>
            {
                entity.HasKey(e => e.MovieId);

                entity.ToTable("tbl_Movie");

                entity.HasIndex(e => e.MovieName, "IX_tbl_Movie")
                    .IsUnique();

                entity.Property(e => e.MovieId).HasColumnName("MovieID");

                entity.Property(e => e.ActorId).HasColumnName("ActorID");

                entity.Property(e => e.DateOfRealese).HasColumnType("date");

                entity.Property(e => e.MovieName)
                    .HasMaxLength(100)
                    .IsFixedLength();

                entity.Property(e => e.ProducerId).HasColumnName("ProducerID");
            });

            modelBuilder.Entity<TblProducer>(entity =>
            {
                entity.HasKey(e => e.ProducerId);

                entity.ToTable("tblProducer");

                entity.Property(e => e.ProducerId)
                    .ValueGeneratedNever()
                    .HasColumnName("ProducerID");

                entity.Property(e => e.Compony).HasMaxLength(100);

                entity.Property(e => e.Dob)
                    .HasColumnType("date")
                    .HasColumnName("DOB");

                entity.Property(e => e.Gender).HasMaxLength(10);

                entity.Property(e => e.ProducerName).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}