// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieAPI_Context.Model
{
    public partial class TblActor
    {
        public int ActorId { get; set; }
        public string ActorName { get; set; }
        public string Gender { get; set; }
        public DateTime? Dob { get; set; }
    }
}