// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieAPI_Context.Model
{
    public partial class TblProducer
    {
        public int ProducerId { get; set; }
        public string ProducerName { get; set; }
        public DateTime? Dob { get; set; }
        public string Gender { get; set; }
        public string Compony { get; set; }
    }
}